import createHttpMethodReducer from './utils/createHttpMethodReducer';

export {default as listen} from './listen';
export {default as composeRoutes} from './composeRoutes';
export {default as composeRoutesLeft} from './composeRoutesLeft';
export {default as sendFile} from './sendFile';
export {default as setHeader} from './setHeader';
export {default as dir} from './dir';

export const acl = createHttpMethodReducer('ACL');
export const bind = createHttpMethodReducer('BIND');
export const checkout = createHttpMethodReducer('CHECKOUT');
export const connect = createHttpMethodReducer('CONNECT');
export const copy = createHttpMethodReducer('COPY');
export const del = createHttpMethodReducer('DELETE');
export {del as delete};
export const get = createHttpMethodReducer('GET');
export const head = createHttpMethodReducer('HEAD');
export const link = createHttpMethodReducer('LINK');
export const lock = createHttpMethodReducer('LOCK');
export const merge = createHttpMethodReducer('MERGE');
export const mkactivity = createHttpMethodReducer('MKACTIVITY');
export const mkcalendar = createHttpMethodReducer('MKCALENDAR');
export const mkcol = createHttpMethodReducer('MKCOL');
export const move = createHttpMethodReducer('MOVE');
export const msearch = createHttpMethodReducer('M-SEARCH');
export const notify = createHttpMethodReducer('NOTIFY');
export const options = createHttpMethodReducer('OPTIONS');
export const patch = createHttpMethodReducer('PATCH');
export const post = createHttpMethodReducer('POST');
export const propfind = createHttpMethodReducer('PROPFIND');
export const proppatch = createHttpMethodReducer('PROPPATCH');
export const purge = createHttpMethodReducer('PURGE');
export const put = createHttpMethodReducer('PUT');
export const rebind = createHttpMethodReducer('REBIND');
export const report = createHttpMethodReducer('REPORT');
export const search = createHttpMethodReducer('SEARCH');
export const subscribe = createHttpMethodReducer('SUBSCRIBE');
export const trace = createHttpMethodReducer('TRACE');
export const unbind = createHttpMethodReducer('UNBIND');
export const unlink = createHttpMethodReducer('UNLINK');
export const unlock = createHttpMethodReducer('UNLOCK');
export const unsubscribe = createHttpMethodReducer('UNSUBSCRIBE');
